#!/bin/sh
#
# PROVIDE: nanoclaw
# REQUIRE: LOGIN NETWORKING
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf to enable nanoclaw:
#
#   nanoclaw_enable="YES"
#   nanoclaw_user="jims"            # (default: jims)
#   nanoclaw_dir="/path/to/src"     # (default: /home/${nanoclaw_user}/code/nanoclaw/src)
#

. /etc/rc.subr

name="nanoclaw"
rcvar="${name}_enable"

load_rc_config $name

: ${nanoclaw_enable:="NO"}
: ${nanoclaw_user:="jims"}
: ${nanoclaw_dir:="/home/${nanoclaw_user}/code/nanoclaw/src"}

pidfile="/var/run/${name}.pid"
command="/usr/sbin/daemon"
command_args="-f -p ${pidfile} -u ${nanoclaw_user} -o /var/log/nanoclaw.log /usr/local/bin/node ${nanoclaw_dir}/dist/index.js"

run_rc_command "$@"
